### ISSUE TITLE
any chance you'd be interested in adding normalization functions?

### ISSUE THREAD

**Issue by durkie** [ethicnology/ophois#3]
https://github.com/mapbox/graph-normalizer has gone unmaintained for several years, but has some adjacent goals to you with ophois. the annoying thing about graph-normalizer is that it requires geojson input, which is not super conducive to working with OSM data directly. It also implements some similar functionality, but with an emphasis on each input geometry having a corresponding output geometry and generating new feature ids in a reproducible and deterministic manner. 

Just a thought! I'd be interested if so :)

**Comment by ethicnology** [comment]
I will not implement their functions, It looks like their project tries to keep the same format with in-place replacement. Ophoïs does not seek to keep the OSM format, It process huge XML/OSM files to extract the street graph, allows it to be simplified and discretized, but the output graph is designed to be easy to use for the implementation of algorithms such as random walks, multi-agent systems…

I checked their files and there is around 350 lines, I thinks it's better to fork or rewrite it.
