### ISSUE TITLE
OSM mixed multigraph and deleting degree-2 nodes?

### ISSUE THREAD

**Issue by kkdd** [ethicnology/ophois#8]
Hello,
Does Ophois import OSM data as a mixed multigraph?
And I consider that the directionality (and undirectionality) of edges should be cared when deleting degree-2 nodes to simply the graph.

**Comment by ethicnology** [comment]
Hello, Ophois import OSM data as an undirected graph.

If you need to deal with mixed multigraph and directionality, I recommend you to fork the project and [to adapt it](https://github.com/ethicnology/ophois/blob/main/src/graph.rs#L93) to your needs.
